language: node_js
node_js:
  - '10.14.1'
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
  - yarn global add codecov
after_success:
  - codecov
cache:
  yarn: true
